#Simple Ansible Playbook
-
  name: plays
  hosts: all
  tasks: 
    -
      name: Monitor Web Application for 6 Minutes
      hosts: web_server
      command: /opt/monitor_webapp.py
      async: 360
      poll: 0
      register: webapp_result
    -
      name: Monitor Database for 6 Minutes
      hosts: db_server
      command: /opt/monitor_database.py
      async: 360
      poll: 0
      register: database_result
