#Simple Ansible Playbook
- hosts: localhost
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
   - name: ensure apache is at the latest version
     yum:
           name: httpd
           state: latest
     register: httpd_installation_status
   - name: write the apache config file
     template:
         src: /srv/httpd.j2
         dest: /etc/httpd.conf
     notify:
        - restart apache
   - name: ensure apache is running
     service:
          name: httpd
          state: started
     register: httpd_status
  handlers:
    - name: restart apache
      service:
           name: httpd
           state: restarted
      register: httpd_restart_status
